### PR TITLE
Handle string escapes

### PR DESCRIPTION
**Pull request by jamii**
Before:

Before

After:

After

### CODE REVIEW

**Comment by jballanc** [comment]
Honest question: is there a way to write tests for highlighting like this in Emacs?

**Comment by jamii** [comment]
I'm sure I saw some tests when I was looking for examples for this patch, but I can't find them again.

**Comment by yuyichao** [comment]
I believe the tests are here https://github.com/JuliaEditorSupport/julia-emacs/blob/344e6c2a32b528eef87165ac32151990193a70f1/julia-mode-tests.el#L406

**Comment by jamii** [comment]
Now there is a test :)

**Comment by jamii** [comment]
Note this doesn't fix https://github.com/JuliaEditorSupport/julia-emacs/issues/15

**Comment by yuyichao** [comment]
> Note this doesn't fix #15

Yeah, I know. I assume it does fix #55 though, which was a dup of the issue mentioned in https://github.com/JuliaEditorSupport/julia-emacs/issues/15#issuecomment-315607776.

**Pull request merged**
