### PR TITLE
fully functional julia repl in emacs

### PR DESCRIPTION
**Pull request by gaika**
create fully functional repl in emacs using screen and term mode. send line or buffer from to repl for evaluation.

### CODE REVIEW

**Comment by gaika** [comment]
just found julia-repl https://github.com/tpapp/julia-repl

**Comment by tpapp** [comment]
If you think that your solution implements something missing from https://github.com/tpapp/julia-repl (which is still experimental), please let me know, I would be happy to cooperate.  PRs are welcome.

**Comment by gaika** [comment]
The only difference is that julia process is run under screen which gives better terminal emulation. There's no need to modify global term properties and all keys work out of the box.

**Comment by tpapp** [comment]
@gaika: Thanks for the suggestion. I added an option for `julia-repl` to use screen when available, in the latest master.

**Pull request closed without merging**
