### PR TITLE
Run CI using emacs 25

### PR DESCRIPTION
**Pull request by non-Jedi**

### CODE REVIEW

**Comment by tpapp** [comment]
AFAIK Travis has bionic:

https://docs.travis-ci.com/user/reference/bionic/

Can you please try that instead of using a PPA?

**Comment by non-Jedi** [comment]
We'd lose testing on 23 then I think. To my mind, if we're supporting old emacs that's much more likely to break without anyone noticing than 25/26. One alternative is that we could use flycheck's setup instead? https://github.com/flycheck/emacs-travis

**Comment by tpapp** [comment]
I think that dropping support for Emacs 23 would be the way to go. I opened a discussion in #86.

**Comment by tpapp** [comment]
Thanks for calling attention to this. Closed this in favor of #95, but if you want to take a stab at setting up CI with emacs-travis, a PR would be appreciated.

**Pull request closed without merging**
